name: build-main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'semeru'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        gradle-version: '6.8.2'

    - name: Build and publish to Maven local
      working-directory: ./dev.galasa.simbank
      run: gradle clean build publishToMavenLocal

    - name: Upload local maven repository
      uses: actions/upload-artifact@v4
      with:
        name: maven-local
        path: ~/.m2/repository

  run-tests-with-galasactl:
    permissions:
      contents: read
    env:
      GALASA_HOME: ${{ github.workspace }}/.galasa
    runs-on: ubuntu-latest
    needs: build-tests
    steps:

    - name: Clone the simplatform repository
      uses: actions/checkout@v4
      with:
        repository: eamansour/simplatform
        path: ${{ github.workspace }}/simplatform

    - name: Build SimBank application
      working-directory: ${{ github.workspace }}/simplatform
      run: |
        ./build-locally.sh

    - name: Download local maven repository
      uses: actions/download-artifact@v4
      with:
        name: maven-local
        path: ${{ github.workspace }}/.m2/repository

    - name: Initialise a local Galasa environment
      uses: eamansour/galasactl-action@v1
      with:
        galasactl_args: |-
          local init
          --log -

    - name: Run the dev.galasa.simbank tests
      uses: eamansour/galasactl-action@v1
      with:
        galasactl_args: |-
          runs submit local
          --obr mvn:dev.galasa.simbank/dev.galasa.simbank.obr/0.0.1/obr
          --class dev.galasa.simbank.tests/dev.galasa.simbank.tests.SimBankIVT
          --localMaven file:///github/workspace/.m2/repository
          --log -

    - name: Upload Galasa test results
      uses: actions/upload-artifact@v4
      with:
        name: galasa-ras
        path: ${{ env.GALASA_HOME }}/ras
