name: build-main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'semeru'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        gradle-version: '6.8.2'

    - name: Build and publish to Maven local
      working-directory: ./dev.galasa.example.banking
      run: gradle clean build publishToMavenLocal

  run-tests-with-galasactl:
    runs-on: ubuntu-latest
    needs: build-tests
    permissions:
      contents: read
    steps:
    - name: Get the version of galasactl
      uses: eamansour/galasactl-action@v1
      with:
        galasactl_args: |-
          --version
    - name: Initialise a local Galasa environment
      uses: eamansour/galasactl-action@v1
      with:
        galasactl_args: |-
          local init
          --log -
    - name: Run the dev.galasa.example.banking tests
      uses: eamansour/galasactl-action@v1
      with:
        galasactl_args: |-
          runs submit local
          --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/obr
          --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccount
          --log -